name: Docker Test, Build, and Push

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Deno
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x # Use the latest stable version of Deno

      # Run Deno tests
      - name: Run Deno tests
        run: |
          deno test

      # Log in to Docker Hub or GitHub Container Registry
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Set this in your repository secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Set this in your repository secrets

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t vmandic/rotvar-algo:latest .

      # Push the Docker image to the registry
      - name: Push Docker image
        run: |
          docker push vmandic/rotvar-algo:latest